iverilog -o QC_LDPC_ENCODER COUNTER_6BIT.v COUNTER_7BIT.v CYCLIC_SHIFT_REGISTER_88BIT.v G_MATRIX_MEMORY.v QC_LDPC_CONTROL_PATH.v QC_LDPC_DATA_PATH.v QC_LDPC_ENCODER_TEST_BENCH.v SHIFT_REGISTER_88BIT.v SRAA_88BIT.v;
vvp QC_LDPC_ENCODER > verilog_results.txt;
gtkwave QC_LDPC_ENCODER.vcd;
