iverilog -o QC_LDPC_ENCODER COUNTER_2BIT.v COUNTER_5BIT.v CYCLIC_SHIFT_REGISTER_16BIT.v MUX_31.v QC_LDPC_CONTROL_PATH.v QC_LDPC_DATA_PATH.v QC_LDPC_ENCODER_TEST_BENCH.v SHIFT_REGISTER_16BIT.v SRAA_16BIT.v;
vvp QC_LDPC_ENCODER;
gtkwave QC_LDPC_ENCODER.vcd;
